spring.application.name=chat-application

spring.security.user.name=user
spring.security.user.password=user


spring.datasource.url=jdbc:h2:mem:chatdb

spring.h2.console.enabled=true

spring.h2.console.path=/h2-console

spring.datasource.username=sa
spring.datasource.password=sa
spring.datasource.driver-class-name=org.h2.Driver

spring.jpa.hibernate.ddl-auto=update

jwt.secret=7d8f9a2b4c6e8f1a3d5b7c9e2f4a6b8d7e9f1a3c5b7d9e2f4a6c8e1b3d5f7a9